#!/usr/bin/env python

## { alterEGO Linux: "Open the vault of knowledge" } ----------------------- ##
##                                                                           ##
## alterEGOtools/sysutils.py                                                 ##
##   created        : 2021-11-10 11:42:58 UTC                                ##
##   updated        : 2021-11-10 11:43:07 UTC                                ##
##   description    : Default configuration.                                 ##
## _________________________________________________________________________ ##

from collections import namedtuple

Package = namedtuple('Package', ['name', 'repository', 'mode'])
packages = [
    Package('alsa-utils', 'official', 'minimal'),
    Package('arp-scan', 'official', 'hack'),
    Package('base', 'official', 'bare'),
    Package('base-devel', 'official', 'bare'),
    Package('bash-completion', 'official', 'minimal'),
    Package('bat', 'official', 'minimal'),
    Package('bc', 'official', 'minimal'),
    Package('bind', 'official', 'hask'),
    Package('binwalk', 'official', 'hack'),
    Package('bleachbit', 'official', 'minimal'),
    Package('bpytop', 'official', 'hack'),
    Package('brave-bin', 'aur', 'minimal'),
    Package('burpsuite', 'aur', 'hack'),
    Package('cmatrix', 'official', 'hack'),
    Package('code', 'official', 'minimal'),
    Package('cronie', 'official', 'minimal'),
    Package('dirbuster', 'aur', 'hack'),
    Package('docker', 'official', 'hack'),
    Package('dos2unix', 'official', 'minimal'),
    Package('dunst', 'official', 'minimal'),
    Package('easy-rsa', 'official', 'beast'),
    Package('entr', 'official', 'minimal'),
    Package('exfat-utils', 'official', 'hack'),
    Package('feh', 'official', 'minimal'),
    Package('ffmpeg', 'official', 'minimal'),
    Package('firefox', 'official', 'minimal'),
    Package('freerdp', 'official', 'minimal'),
    Package('fzf', 'official', 'minimal'),
    Package('gimp', 'official', 'bare'),
    Package('git', 'official', 'bare'),
    Package('gnu-netcat', 'official', 'hack'),
    Package('go', 'official', 'minimal'),
    Package('gobuster-git', 'aur', 'hack'),
    Package('grc', 'official', 'hack'),
    Package('gromit-mpx-git', 'aur', 'beast'),
    Package('grub', 'official', 'bare'),
    Package('htop', 'official', 'minimal'),
    Package('i3-gaps', 'official', 'minimal'),
    Package('i3blocks', 'official', 'minimal'),
    Package('imagemagick', 'official', 'minimal'),
    Package('inkscape', 'official', 'minimal'),
    Package('inxi', 'aur', 'hack'),
    Package('john', 'official', 'hack'),
    Package('jq', 'official', 'minimal'),
    Package('jre11-openjdk', 'official', 'hack'),
    Package('libreoffice-fresh', 'official', 'minimal'),
    Package('librespeed-cli-bin', 'aur', 'minimal'),
    Package('linux', 'official', 'bare'),
    Package('lynx', 'official', 'bare'),
    Package('man-db', 'official', 'minimal'),
    Package('man-pages', 'official', 'minimal'),
    Package('mariadb-clients', 'official', 'hack'),
    Package('metasploit', 'official', 'hack'),
    Package('mlocate', 'official', 'minimal'),
    Package('mtools', 'official', 'minimal'),
    Package('mtr', 'official', 'hack'),
    Package('net-tools', 'official', 'hack'),
    Package('networkmanager', 'official', 'bare'),
    Package('nfs-utils', 'official', 'minimal'),
    Package('nikto', 'official', 'hack'),
    Package('nmap', 'official', 'hack'),
    Package('ntfs-3g', 'official', 'minimal'),
    Package('openssh', 'official', 'minimal'),
    Package('openvpn', 'official', 'beast'),
    Package('p7zip', 'official', 'minimal'),
    Package('pandoc-bin', 'aur', 'minimal'),
    Package('pavucontrol', 'official', 'minimal'),
    Package('perl-image-exiftool', 'official', 'hack'),
    Package('php', 'official', 'hack'),
    Package('polkit-gnome', 'official', 'minimal'),
    Package('postgresql', 'official', 'hack'),
    Package('powershell-bin', 'aur', 'hack'),
    Package('pptpclient', 'official', 'minimal'),
    Package('pulseaudio', 'official', 'minimal'),
    Package('pv', 'official', 'hack'),
    Package('python-beautifulsoup4', 'official', 'hack'),
    Package('python-pandas', 'official', 'hack'),
    Package('python-pip', 'official', 'bare'),
    Package('python-pyaml', 'official', 'hack'),
    Package('python-rich', 'official', 'hack'),
    Package('qrencode', 'official', 'hack'),
    Package('qterminal', 'official', 'hack'),
    Package('qtile', 'official', 'hack'),
    Package('ranger', 'official', 'minimal'),
    Package('remmina', 'official', 'minimal'),
    Package('rsync', 'official', 'minimal'),
    Package('rustscan', 'aur', 'hack'),
    Package('screen', 'official', 'minimal'),
    Package('screenkey', 'official', 'hack'),
    Package('shellcheck', 'official', 'hack'),
    Package('simple-mtpfs', 'aur', 'minimal'),
    Package('sqlitebrowser', 'official', 'hack'),
    Package('sxiv', 'official', 'minimal'),
    Package('tcpdump', 'official', 'hack'),
    Package('tesseract', 'official', 'hack'),
    Package('tesseract-data-eng', 'official', 'hack'),
    Package('tesseract-data-fra', 'official', 'hack'),
    Package('thunar', 'official', 'minimal'),
    Package('thunar-volman', 'official', 'minimal'),
    Package('tidy', 'official', 'hack'),
    Package('tk', 'official', 'hack'),
    Package('tmux', 'official', 'minimal'),
    Package('traceroute', 'official', 'hack'),
    Package('transmission-gtk', 'official', 'minimal'),
    Package('tree', 'official', 'minimal'),
    Package('ufw', 'official', 'minimal'),
    Package('unrar', 'official', 'minimal'),
    Package('unzip', 'official', 'minimal'),
    Package('usbutils', 'official', 'minimal'),
    Package('vim', 'official', 'bare'),
    Package('virtualbox-guest-utils', 'official', 'minimal'),
    Package('w3m', 'official', 'minimal'),
    Package('wfuzz-git', 'aur', 'hack'),
    Package('wget', 'official', 'bare'),
    Package('whois', 'official', 'hack'),
    Package('wireshark-qt', 'official', 'hack'),
    Package('xclip', 'official', 'minimal'),
    Package('xcompmgr', 'official', 'minimal'),
    Package('xdotool', 'official', 'minimal'),
    Package('xfce4-terminal', 'official', 'minimal'),
    Package('xorg-server', 'official', 'minimal'),
    Package('xorg-xinit', 'official', 'minimal'),
    Package('xterm', 'official', 'minimal'),
    Package('youtube-dl', 'official', 'hack'),
    Package('zaproxy', 'official', 'hack'),
    Package('zathura', 'official', 'minimal'),
    Package('zathura-pdf-mupdf', 'official', 'minimal'),
    Package('zbar', 'official', 'hack'),
    ]

## FIN _____________________________________________________________ ¯\_(ツ)_/¯
